### ISSUE TITLE
Perhaps, test `test_estimate_bandwidth_1sample` can be already unmuted for aarch64 and ppc64le

### ISSUE THREAD

**Issue by ayushkovskiy** [conda-forge/scikit-learn-feedstock#106]
Issue:

Test `test_estimate_bandwidth_1sample` is currently muted for `aarch64` and `ppc64le`:
https://github.com/conda-forge/scikit-learn-feedstock/blob/a98d911ad0c9329c96968fb3f11c5974191311a4/recipe/meta.yaml#L51

I am not an expert and I didn't go deep into details, but the original [issue](https://github.com/scikit-learn/scikit-learn/issues/10561) seems to be resolved: https://github.com/scikit-learn/scikit-learn/pull/12612. Perhaps, the test can be unmuted for these architectures.

**Comment by rth** [comment]
> Perhaps, the test can be unmuted for these architectures.

Yes, you are right -- this was fixed for v0.22 in https://github.com/conda-forge/scikit-learn-feedstock/pull/113. Closing. Thanks for reporting!
