### ISSUE TITLE
Python 3.8 build for v0.21.3

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/scikit-learn-feedstock#119]
Working on the `lightgbm` feedstock, upstream they have put a requirement on scikit-learn `<0.21.3`. Currently, there is no build of this feedstock for `0.21.x` that supports py3.8. There is a build on defaults for py3.8, but only on linux. Is there any chance that we could support py3.8 on this older version?

**Comment by adrinjalali** [comment]
AFAIK the answer is no, or at least I haven't seen any effort on that front. Unless somebody cares to do the backports needed for 3.8 and push a release. @ogrisel were involved in the py3.8 fixes? I vaguely remember you saying they weren't many, or they were on the joblib side. How easy is it to push a 3.8 build for 0.21.X?

**Comment by h-vetinari** [comment]
If someone from @conda-forge/scikit-learn were to create a branch at https://github.com/conda-forge/scikit-learn-feedstock/commit/a98d911ad0c9329c96968fb3f11c5974191311a4 (last commit before 0.22 merged), I'd be happy to try a PR that builds 0.21.3 for python 3.8.

I'm hitting this issue in various ways atm...

**Comment by adrinjalali** [comment]
Closing this since we're not maintaining 0.21 anymore.
