### ISSUE TITLE
Should scikit-learn link against LLVM OpenMP instead of GNU OpenMP

### ISSUE THREAD

**Issue by knedlsepp** [conda-forge/scikit-learn-feedstock#136]
Issue:
I don't have a minimal reproducer for this but I have the suspicion that linking against GNU OpenMP might the same undesired effects in scikit-learn as was observed and fixed for OpenBLAS here: https://github.com/conda-forge/openblas-feedstock/pull/92 

I'm thus wondering if an equivalent change should also be made here.

Ping @beckermr.

**Comment by knedlsepp** [comment]
Similar issue for scikit-image: https://github.com/conda-forge/scikit-image-feedstock/issues/69

**Comment by beckermr** [comment]
cc @conda-forge/core @isuruf 

Generally, we build against gnu openmp and then let users swap in llvm at run time on linux. I didn't follow the openblas issue above, but hopefully, someone else knows what happened there.

**Comment by knedlsepp** [comment]
@beckermr Sorry, I thought you were the author of the openmp fix. (That's why I tagged you)
