### ISSUE TITLE
In `pip check` scikit-learn version 1.3.2 is reported as 1.4.dev0

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/scikit-learn-feedstock#237]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I installed: 
```
scikit-learn                     1.3.2  py39ha22ef79_0       conda-forge/linux-64       9MB
```

But when I call `pip check` I get the following error message: 
```
... has requirement scikit-learn==1.3.2, but you have scikit-learn 1.4.dev0.
```

**Comment by glemaitre** [comment]
Thanks for reporting. We had a wrong tag on the GitHub repository. We release a new binaries with build number 1. We requested to tag the build 0 as broken packages: https://github.com/conda-forge/admin-requests/pull/851
