### ISSUE TITLE
Meson + cross-compilation for Mac ARM

### ISSUE THREAD

**Issue by jeremiedbb** [conda-forge/scikit-learn-feedstock#256]
For 1.5.0rc1 I tried to switch to meson to build scikit-learn since it's now the default build system (https://github.com/conda-forge/scikit-learn-feedstock/pull/254). It worked for all builds but the Mac ARM ones (e.g. [log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=928211&view=logs&jobId=385a3385-ae8b-54d1-9abe-3c614f74cb73&j=385a3385-ae8b-54d1-9abe-3c614f74cb73&t=a5f9d343-149e-5621-6ab9-f0278009be04)). The issue seems to be related to the combination of meson + cross-compilation.

cc/ @lesteve, maybe you'll have some hints on how to fix this

**Comment by ogrisel** [comment]
I did launch the tests on scikit-learn installed with:

```
conda install conda-forge/label/scikit-learn_rc::scikit-learn=1.5.0rc1
```

and everything is green. How did you generate that build?

**Comment by jeremiedbb** [comment]
I did it in this PR https://github.com/conda-forge/scikit-learn-feedstock/pull/258, after many trials and errors. And once I made it work, I found https://github.com/conda-forge/scikit-learn-feedstock/pull/250 that was doing essentially the same thing :)
We can close this issue now
