### ISSUE TITLE
no openblas 0.2.19 builds

### ISSUE THREAD

**Issue by zym1010** [conda-forge/scikit-learn-feedstock#28]
similar issues as in https://github.com/conda-forge/scipy-feedstock/issues/39

**Comment by jakirkham** [comment]
Not exactly. We hadn't merged the pinning PRs yet as there were downstream issues with NumPy and SciPy that still needed sorting.

In any event, thanks for the reminder.

**Comment by jakirkham** [comment]
Have merged the pinning PRs. Should be ready in a couple of hours hopefully.

**Comment by jakirkham** [comment]
Appear to be uploaded. Please let us know if there are any other issues.
