### ISSUE TITLE
Build for using mkl?

### ISSUE THREAD

**Issue by will133** [conda-forge/scikit-learn-feedstock#72]
Issue:  I'm trying to install scikit-learn along with numpy and scipy with mkl.  However, it seems like for version 0.19.2 there is only a openblas build in anaconda and conda-forge.  This would then conflict with numpy and scipy with the blas_mkl tracked feature (when blas=1.0=mkl is installed).  I see from the variant that the mkl can be specified.  Is there any plan to support a mkl build in conda in the future?

**Comment by amueller** [comment]
There's no MKL on conda-forge. There should be on the main conda channel. If there's not, please raise the issue with anaconda.

**Comment by ocefpaf** [comment]
> There's no MKL on conda-forge. There should be on the main conda channel. If there's not, please raise the issue with anaconda.

Yep. Closing this b/c as far as I know `conda-forge` cannot ship/build `mkl`. You'll have to rely on the `defaults` channel for that.
