### ISSUE TITLE
windows builds?

### ISSUE THREAD

**Issue by amueller** [conda-forge/scikit-learn-feedstock#8]
So is the problem with windows builds that there's no OpenBlas on windows so far?
Not supporting windows is pretty bad :(

**Comment by jakirkham** [comment]
:cry: Sadly accurate. I'd love for suggestions on the Windows BLAS issue, but it is a bit of a mess particularly with VC14.

xref: https://github.com/conda-forge/openblas-feedstock/issues/2

**Comment by rth** [comment]
If I understood correctly the OpenBlas has been built on Windows (the above linked issues was solved). 

See https://github.com/conda-forge/scipy-feedstock/issues/80 for the status of building Scipy for Windows

cc @lesteve

**Comment by lesteve** [comment]
Nice, so I guess this should be reasonably straightforward to enable Windows builds!

**Comment by rth** [comment]
Not as long as the scipy Windows build issue is not resolved..

**Comment by lesteve** [comment]
Ah right ...

**Comment by ocefpaf** [comment]
This was solved some time ago but we forgot to close the issue.

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/scikit-learn-feedstock/pull/90
